### ISSUE TITLE
get slides (and R Markdown examples) to Rick by 4pm today (Tuesday)

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/tidy-databases#11]

**Comment by beanumber** [comment]
I think I'm done. Where do you want your examples to fit in?

**Comment by nicholasjhorton** [comment]
How about before the performance issues discussion?

Nick

> On Nov 14, 2017, at 1:26 PM, Ben Baumer <notifications@github.com> wrote:
> 
> I think I'm done. Where do you want your examples to fit in?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by beanumber** [comment]
Yup, will do.

**Comment by nicholasjhorton** [comment]
Oops. I was hoping the examples could go out as well. We will want to mention this. 

Should we copy the GitHub slide so it shows up early as well as at the end?

All the best,

Nick
