### ISSUE TITLE
Take screenshots of the five verb pictograms from cheatsheet

### ISSUE THREAD

**Issue by beanumber** [beanumber/tidy-databases#2]
https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf

Is this something @nicholasjhorton could do? One for each of the five verbs, plus `group_by()`. Roughly a 16x10 aspect ratio?

**Comment by nicholasjhorton** [comment]
is this the aspect ratio you are after?

https://github.com/beanumber/tidy-databases/commit/266edbd3d574ee16f0fca0ac81e655d7763cd928

**Comment by beanumber** [comment]
These are perfect. Thanks!
