### ISSUE TITLE
review Voss example (public facing database)

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/tidy-databases#3]
see https://github.com/beanumber/tidy-databases/tree/master/examples

**Comment by beanumber** [comment]
This looks good. I would recommend:

* replacing `mosaic` with `tidyverse`
* every pipe end a line
* every `+` ends a line

Do you want me to make these changes?

**Comment by nicholasjhorton** [comment]
Can you please make these changes in sql-example1.Rmd?  I'll then mirror those in sql-example2.Rmd.

Nick

> On Nov 14, 2017, at 1:35 PM, Ben Baumer <notifications@github.com> wrote:
> 
> This looks good. I would recommend:
> 
> 	• replacing mosaic with tidyverse
> 	• every pipe end a line
> 	• every + ends a line
> Do you want me to make these changes?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by beanumber** [comment]
What does this mean (in "sql-example2.Rmd"):

> Alternatively, a connection can be made to the server by creating a series of `dplyr` table objects. 

?

Also, is there a reason that you explicitly left `warning=TRUE` in one of these chunks?
